apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-kubernetes-hello-world-demo
  labels:
    app: kubernetes-hello-world-demo
spec: 
  template: 
    metadata: 
      labels: 
        app: kubernetes-hello-world-demo
    spec: 
        containers: 
          - name: container-kubernetes-hello-world-demo
            image: cloudblockandbeyond/image_kubernetes-hello-world-demo:1.0.0
            imagePullPolicy: Always
            ports:
              - name: http
                protocol: TCP
                containerPort: 80
            env:
              - name: RuntimeEnvironment
                value: "Kubernetes"
            resources:
              requests: 
                memory: "64Mi"
                cpu: "250m"
              limits: 
                memory: "128Mi"
                cpu: "500m"
  replicas: 2
  selector: 
    matchLabels: 
      app: kubernetes-hello-world-demo