version: '3.6'

services: 

  kubernetes-hello-world-demo: 
    build: 
      context: 'kubernetes-hello-world-demo'
      dockerfile: Dockerfile
    image: 'docker.io/cloudblockandbeyond/image-kubernetes-hello-world-demo:1.0.0'
    container_name: 'container-kubernetes-hello-world-demo'
    ports:
      - "5300:80/tcp"