apiVersion: v1
kind: Service
metadata: 
  name: service-kubernetes-hello-world-demo
  labels: 
    app: kubernetes-hello-world-demo
spec: 
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  selector: 
    app: kubernetes-hello-world-demo